x-bot-common: &bot-common
  container_name: got
  env_file:
    - .env
  environment:
    DB_URL: postgres://postgres:postgres@postgres:5432/telebot?sslmode=disable
    REDIS_ADDR: redis:6379
  volumes:
    - ./.env:/app/.env:ro
  depends_on:
    - postgres
    - redis
  networks:
    - bot-network
  restart: unless-stopped

services:
  bot:
    <<: *bot-common
    image: ghcr.io/tkozakas/got:latest
    profiles: ["prod"]

  bot-dev:
    <<: *bot-common
    build:
      context: .
      dockerfile: Dockerfile
    image: got:local
    profiles: ["dev"]

  postgres:
    container_name: bot-postgres
    image: postgres:16-alpine
    ports:
      - "54320:5432"
    environment:
      POSTGRES_DB: telebot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bot-network
    restart: unless-stopped

  redis:
    container_name: bot-redis
    image: redis:alpine
    ports:
      - "63790:6379"
    volumes:
      - redis-data:/data
    networks:
      - bot-network
    restart: unless-stopped

networks:
  bot-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
